export const metadata = {
  title: 'ChatGPT Clone',
  description: 'Generated by Next.js',
}

export default function Head() {
  return (
    <>
      <title>ChatGPT Clone</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <link rel="icon" href="/favicon.ico" />
    </>
  )
}